### ISSUE TITLE
Error libssl

### ISSUE THREAD

**Issue by briscula** [harrisbaird/dockerfiles#2]
Hi, getting error when deploying a spider:

Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /usr/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so)\\n

I solved it by adding `RUN apk --update add openssl-dev` in my dockerfile. 

I am sure there might be a better solution.

Regards

**Comment by harrisbaird** [comment]
You're right, `openssl-dev` was temporarily installed but removed but after installing the python dependencies. I've added `libssl1.0` to `RUNTIME_PACKAGES` so it's always available and fixes the problem.
